name: remote ssh command
on: [push]
jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VORYS_HOST }}
        username: ${{ secrets.VORYS_USER }}
        port: 22
        script: |
          cd ~
          touch hello.txt
          echo "Hello world" > hello.txt
        key:  ${{ secrets.VORYS_PRIVATE_KEY }}
