name: remote ssh command
on: [push]
jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        script: cd ${{ secrets.PROJECT_PATH }} && git pull
        key:  ${{ secrets.PRIVATE_KEY }}
