name: remote ssh command
on: [push]
jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone repo
      uses: appleboy/ssh-action@master
      env:
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.VORYS_HOST }}
        username: ${{ secrets.VORYS_USER }}
        port: 22
        envs: SHA
        script: |
          cd ~
          git clone https://github.com/Megass5038/technology-labs.git $SHA
          scp -i ~/.ssh/id_rsa -r /home/ec2-user/$SHA ec2-user@3.135.11.59:/home/ec2-user/projects/$SHA
        key:  ${{ secrets.VORYS_PRIVATE_KEY }}
